name: Update GitHub Snake

on:
  workflow_dispatch:       # Permite executar manualmente
  schedule:
    - cron: '0 */6 * * *'  # Roda a cada 6 horas (ajuste se quiser)
  push:
    branches:
      - main              # Dispara quando houver push na main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Gera a cobrinha (versão light)
      - name: Generate Snake (Light Mode)
        uses: Platane/snk@master
        with:
          github_user_name: kleberton-santos  # Seu nome de usuário
          svg_out_path: dist/snake.svg
          github_feed: "contribution"  # OBRIGATÓRIO para pegar commits

      # Gera a cobrinha (versão dark)
      - name: Generate Snake (Dark Mode)
        uses: Platane/snk@master
        with:
          github_user_name: kleberton-santos
          svg_out_path: dist/snake-dark.svg
          colors: "bg:0f172a! gr:334155! gu:475569! pu:64748b! op:f1f5f9"
          github_feed: "contribution"

      # Envia para o branch 'output'
      - name: Deploy Snake to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          keep_files: true  # Mantém arquivos antigos
