name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # A cada 12 horas
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Gera a versão light
      - uses: Platane/snk@master
        with:
          github_user_name: kleberton-santos
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      # Gera a versão dark
      - uses: Platane/snk@master
        with:
          github_user_name: kleberton-santos
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          colors: "bg:0f172a! gr:334155! gu:475569! pu:64748b! op:f1f5f9"

      # Publica no branch output
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          keep_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
